# Generated by Django 2.2.4 on 2019-08-27 06:30

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('workshopapp', '0003_feedbackdata'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enquairymodel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('mobile', models.BigIntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('gender', models.CharField(max_length=10)),
                ('course', multiselectfield.db.fields.MultiSelectField(choices=[('PY', 'python'), ('DJ', 'django'), ('RA', 'restapi'), ('FL', 'flask'), ('UI', 'ui')], max_length=14)),
                ('shifts', multiselectfield.db.fields.MultiSelectField(choices=[('Morning', 'Morning shift'), ('Afternoon', 'Afternoon shift'), ('Evening', 'Evening shift'), ('Night', 'Night shift')], max_length=31)),
                ('start_date', models.DateTimeField()),
            ],
        ),
    ]
